### PR TITLE
fixes botanist access

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
botanist man no have access

me fix
made as a result of https://github.com/Eclipse-Station/NEV-Northern-Light/issues/40

### CODE REVIEW

**Comment by drexample** [comment]
You should probably make it uhhh
Normal access on their ID 
Instead of cruciform

**Comment by bearrrrrrrr** [comment]
@drexample I actually don't know what the plan for lore or any of that bit is (if people _want_ them to have a cruciform or not), so I just kept it as cruciform.

Can still change if wanted.

**Comment by bearrrrrrrr** [comment]
changed, now normal access instead of cruciform_access

**Comment by bearrrrrrrr** [comment]
apologies, I am github baby. thank you!

**Pull request merged**
