### PR TITLE
adds another deepmaint room, fixes phoron deepmaint map

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

fixes oopsitsphoron.dmm from not having a door, also lowered actual amount of phoron due to my own concern of it being excessive still.
adds oopsitsbeartraps.dmm

## Why It's Good For The Game

this is good for the game because doors are good. also it adds a deepmaint room. said deepmaint room is a small shelter/hut that is full of garbage and beartraps. 

## Changelog
:cl:
add: added oopsitsbeartraps.dmm
fix: fixed oopsitsphoron.dmm
/:cl:
http://puu.sh/G2rw6/d1f80a6657.jpg
http://puu.sh/G2rvg/4d39532f96.jpg

im gonna cry

### CODE REVIEW

**Comment by EvilJackCarver** [comment]
your changelog won't compile without both :cl: characters in there

**Comment by bearrrrrrrr** [comment]
FORGOT TO ADD OOPS! ALL BEARTRAPS TO THE THINGY

IM CRYING

**Comment by bearrrrrrrr** [comment]
also fixed :cl:

**Comment by EvilJackCarver** [comment]
```
loading cev_eris.dme
loading interface\skin.dmf
loading _CEV_Eris.dmm
loading centcomm.dmm
loading crawler-1.dmm
loading deepmaint-1.dmm
loading deepmaint-2.dmm
loading deepmaint-3.dmm
loading asteroid.dmm
loading spacefortress.dmm
loading spaceruins.dmm
saving cev_eris.dmb (DEBUG mode)
cev_eris.dmb - 0 errors, 0 warnings (7/1/20 5:11 pm)
```

Compiled successfully, so we can ignore the CI failure in this case. Gonna review momentarily.

**Comment by bearrrrrrrr** [comment]
CI failure might have been from my initial push, 'I'm baby', where I did not actually execute map merger.

That was remedied in 'I'm going to cry'.

**Comment by EvilJackCarver** [comment]
No, because each new commit should trigger a new CI build. CI is failing for this pull request, so I manually compiled it.

If you're confused by what I'm talking about, go to another PR and check the 'Checks' tab, and compare it to this one.

**Comment by bearrrrrrrr** [comment]
Oh, I thought CI just checked on initial comitt. You learn erry day.

**Pull request merged**
