### PR TITLE
[WIP] NT dispatcher by EJC

### PR DESCRIPTION
**Pull request by drexample**
## About The Pull Request

Ports the NT DAD code from EStation, and tweaks it to work a bit better. To call someone through discord, ensure the department of who you're trying to call is empty, and then send a request through a request console.

This does not work for Head of Staff desks, this is intentional.

## Why It's Good For The Game

Call people into action. Make rounds fun, call for backup, all that.

## Changelog
🆑 EvilJackCarver
add: Adds the NT Department Alarm Dispatcher! To send a personnel request, send a request console message to an empty department.
/🆑

### CODE REVIEW

**Comment by drexample** [comment]
WHOOPS

**Comment by drexample** [comment]
I just remembered this exists.

**Comment by EvilJackCarver** [comment]
Alright, getting back to work on this. It'll be a few days until it's ready again.

**Comment by EvilJackCarver** [comment]
Righto. Finished testing things, you should be good to add in the code that pushes to Discord, @drexample

**Review by EvilJackCarver — APPROVED** [review]

**Pull request merged**
