### PR TITLE
allows the crafting of glass spears

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
noticed you could craft telespears but not normal spears

glass spears already exist

did this

lol

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
also don't be put off by the idea of someone having access to a weapon this strong this easily, fire extinguishers are insane holy god why are fire extinguishers so good

**Comment by bearrrrrrrr** [comment]
actually maybe i should make it a wired rod instead so you can just shove whatever on the end of it

hmmm

Any thoughts

**Comment by drexample** [comment]
Other spear-like crafts just use rods, so you should probably stick with rods
:v

**Comment by bearrrrrrrr** [comment]
hmm

it feels a bit weird to make it just rod and glass and no other steps
but it makes sense since it's literally just a piece of pointy glass on a stick

**Comment by bearrrrrrrr** [comment]
dunnit

**Pull request merged**
