### PR TITLE
Neck fluff

### PR DESCRIPTION
**Pull request by lukevale**
Adds in neck fluff for all races to make use of if wanted.

Unlike the mane marking it can overlay atop clothing which makes it more viewable and not always hidden under clothing.
Also looks good, and not super scuffed like the mane marking.

## Changelog
:cl:
add:neck fluff beard type.
/:cl:

### CODE REVIEW

**Comment by EvilJackCarver** [comment]
Screenshot?

**Comment by lukevale** [comment]
unknown
unkn2own

**Comment by lukevale** [comment]
I can provide more if you need em

**Comment by EvilJackCarver** [comment]
If you could get one in-game with a hardsuit on, that'll be all I need. The main purpose of me asking for pictures was to make sure it was tested.

**Comment by lukevale** [comment]
image
image

**Comment by lukevale** [comment]
The helment blocks facial hair.
Anything that blocks facial hair will black the mane.

**Comment by lukevale** [comment]
image

**Review by EvilJackCarver — APPROVED** [review]

**Comment by drexample** [comment]
fleff

**Pull request merged**
